src_dict = {'EMS':'EMS', 'ED':'Emergency Departments', 'ME':'Medical Examiner'}
center_dict = {'Detroit': '{lat: 42.35, lng: -83.09}',
              'Wayne': '{lat: 42.24, lng: -83.22}',
              'Kent': '{lat: 43.03, lng: -85.53}',
              'Muskegon': '{lat: 43.30, lng: -86.17}',
              'Washtenaw': '{lat: 42.25, lng: -83.84}',
              }
race_dict = {'B':'African American',
             'Black or African American':'Black',
             'African American / Black':'Black',
             'W':'White',
             'White, Not Recorded':'White',
             'Patient Refused':'Unknown',
             '1':'Unknown',
             '2':'Unknown',
             '6':'Unknown',
             '7':'Unknown',
             '8':'Unknown',
             'A':'Unknown',
             'D':'Unknown',
             'Not Recorded':'Unknown',
             'Not Applicable':'Unknown',
             'White, Hispanic or Latino':'Hispanic or Latino',
             'White,Hispanic or Latino':'Hispanic or Latino',
             'Hispanic or Latino, White':'Hispanic or Latino',
             'Hispanic, White':'Hispanic or Latino',
             'Asian, White':'Other',
             'White, Asian':'Other',
             'Asian, Black or African American':'Other',
             'Black or African American, White':'Other',
             'White, Black or African American':'Other',
             'White,Black or African American':'Other',
             'Black or African American, Hispanic or Latino':'Other',
             'Hispanic or Latino, Black or African American':'Other',
             'White, Native Hawaiian or Other Pacific Islander, Asian':'Other',
             'Native Hawaiian or Other Pacific Islander, White':'Other',
             'White, Native Hawaiian or Other Pacific Islander':'Other',
             'White,Native Hawaiian or Other Pacific Islander,Hispanic or Latino,Black or African American,Asian,American Indian or Alaska Native':'Other',
             'White, Native Hawaiian or Other Pacific Islander, Hispanic or Latino, Black or African American, Asian, American Indian or Alaska Native':'Other',
             'Black or African American, American Indian or Alaska Native':'Other',
             'White, Hispanic or Latino, Asian, American Indian or Alaska Native':'Other',
             'Unspecified':'Other',
             'American Indian / Alaskan Native':'American Indian or Alaska Native',
             }
gender_dict = {'F':'Female',
               'M':'Male',
               'U':'Unknown',
               'Unknown (Unable to Determine)':'Unknown',
               'Not Applicable':'Unknown',
               }